-- Create spec schema

CREATE SCHEMA IF NOT EXISTS spec;

GRANT ALL PRIVILEGES ON SCHEMA spec TO spec;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA spec TO spec;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA spec TO spec;